# Generated by Django 5.2.14 on 2026-05-23 00:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pharmacyinventory_pharmacyorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospital',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='hospital_logos/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='prescription_footer',
            field=models.ImageField(blank=True, null=True, upload_to='prescription_footers/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='prescription_header',
            field=models.ImageField(blank=True, null=True, upload_to='prescription_headers/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='prescription_layout',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='HospitalStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('hospital_admin', 'Hospital Admin'), ('director', 'Director'), ('superintendent', 'Superintendent'), ('doctor', 'Doctor')], default='doctor', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='api.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hospital_staff',
                'ordering': ['-created_at'],
                'unique_together': {('hospital', 'user')},
            },
        ),
    ]
