[build]
  base    = "frontend"
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  PUPPETEER_SKIP_DOWNLOAD = "true"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
